# Generated by Django 5.0.6 on 2024-10-11 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def create_initial_data(apps, schema_editor):
    MyModel = apps.get_model('api', 'Event')
    MyModel.objects.create(name='Concierto Movistar', description='''Stiven Mesa Londoño también es El Bendito o como todos lo conocemos: Blessed. El cantante antioqueño es la nueva joya del perreo colombiano. “Hecho en Medellín”, “Siempre Blessed” y “SI SABE” son los tres discos, que en tres años, han forjado una efervescente carrera que ahora lo llevará, en vivo a la Arena Movistar 
                           en una segunda fecha este 19 de octubre.''',imagen='https://movistararena.co/wp-content/uploads/2024/09/borrador-automatico-418.jpg',
                           video='https://www.youtube.com/watch?v=zcw8NlHljF4')
    
class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0008_rename_evento_event_rename_eventousuario_eventuser_and_more'),
    ]
    
    operations = [
        migrations.RunPython(create_initial_data),
    ]
