# Generated by Django 5.0.6 on 2024-10-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '00010_datos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'comentario', 'verbose_name_plural': 'comentarios'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'evento', 'verbose_name_plural': 'eventos'},
        ),
        migrations.AlterModelOptions(
            name='eventuser',
            options={'verbose_name': 'evento-usuario', 'verbose_name_plural': 'eventos-usuarios'},
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Nombre'),
        ),
    ]
